/////////////////////////////////////////////////////
// displayGoogleSheet
// Version 0.6.1
//https://github.umn.edu/dobe0002/GoogleSheetPuller

function displayGoogleSheet(d){var a={docId:"",sheetId:"od6",feedURL:"",containingObj:document.getElementsByTagName("body")[0],error:"",timeout:"",callback:function(){},noResults:function(){console.log("no results returned")},noResultsString:"No data available.",helpersObj:displayGoogleSheetHelper,customFormatting:"",getData:"",getDataClean:"",testing:!1,sheetsId:"",callbackClean:""},b;for(b in d)void 0!=d[b]&&(a[b]=d[b]);""==a.docId&&(a.docId=a.sheetsId);""==a.getDataClean&&""!=a.callbackClean&&
(a.getDataClean=a.callbackClean);b=function(){if(""===a.feedURL){var c="https:";"http:"==location.protocol&&(c="http:");a.feedURL=c+"//spreadsheets.google.com/feeds/cells/"+a.docId+"/"+a.sheetId+"/public/full?alt=json"}!0===a.testing&&console.log("url: "+a.feedURL);a.helpersObj.makeCORSRequest({url:a.feedURL,onload:e,error:a.error,timeout:a.timeout,type:"json"})};var e=function(c){1==a.testing&&console.log("Success.  Json: "+JSON.stringify(c));if(""!=a.getData)a.getData(c);else if("undefined"==typeof c.feed.entry||
0==c.feed.entry.length)a.noResults(),a.containingObj.innerHTML=a.noResultsString;else{for(var b=0,d=0,f=[],e=[],g=[],k=0;k<c.feed.entry.length;k++){var h=c.feed.entry[k];0==k&&(d=h.gs$cell.row);if(h.gs$cell.row==d)f[h.gs$cell.col]=h.content.$t;else{if(h.gs$cell.row!=b&&b!=d&&0!=b){for(j in f)void 0==g[f[j]]&&(g[f[j]]="");e.push(g);g=[]}b=h.gs$cell.row;g[f[h.gs$cell.col]]=h.content.$t}}for(j in f)void 0==g[f[j]]&&(g[f[j]]="");e.push(g);if(""!=a.getDataClean)a.getDataClean(e);else{c="";if(""!=a.customFormatting)c+=
a.customFormatting(e);else{c+="<table>";for(b=0;b<e.length;b++){if(0==b){c+="<thead><tr>";for(j in e[b])c+="<th>"+j+"</th>";c+="</tr></thead>"}c+="<tr>";for(j in e[0])c+="<td>"+e[b][j]+"</td>";c+="</tr>"}c+="</table>"}a.containingObj.innerHTML=c;a.callback()}}};!0!==a.testing&&"version"!=d||console.log("displayGoogleSheet version: 0.6.1");"version"!=d&&(""==a.docId&&""==a.feedURL?console.log("ERROR: No Document ID is defined"):b())}
function getGoogleSheetList(d){var a={docId:"",feedURL:"",error:"",timeout:"",callback:function(){},noResults:function(){console.log("no results returned")},helpersObj:displayGoogleSheetHelper,getData:"",getDataClean:function(a){console.log(JSON.stringify(a))},testing:!1,containingObj:document.getElementsByTagName("body")[0],noResultsString:"No data available.",customFormatting:""},b;for(b in d)void 0!=d[b]&&(a[b]=d[b]);d=function(){if(""==a.feedURL){var c="https:";"http:"==location.protocol&&(c=
"http:");a.feedURL=c+"//spreadsheets.google.com/feeds/worksheets/"+a.docId+"/public/full?alt=json"}!0===a.testing&&console.log("url: "+a.feedURL);a.helpersObj.makeCORSRequest({url:a.feedURL,onload:e,error:a.error,timeout:a.timeout,type:"json"})};var e=function(c){if("undefined"==typeof c.feed.entry||0==c.feed.entry.length)a.noResults();else if(""!=a.getData)a.getData(c);else{for(var b=[],d=0;d<c.feed.entry.length;d++){var e={},l=c.feed.entry[d];e.sheetName=l.title.$t;e.sheetId=/[\/]([^\/]+)$/.exec(l.id.$t)[1];
e.url=l.link[1].href;b.push(e)}1==a.testing&&console.log("sheetArray "+b);a.getDataClean(b);a.callback()}};""==a.docId&&""==a.feedURL?console.log("ERROR: No Document ID is defined"):d()}try{var jqueryIsLoaded=jQuery;(function(d){d.fn.displayGoogleSheet=function(a){return this.each(function(){a.containingObj=this;displayGoogleSheet(a);""!=a.success&&void 0!=a.success&&a.success()})}})(jQuery)}catch(d){}
var displayGoogleSheetHelper={makeCORSRequest:function(d){var a={url:"",method:"GET",onload:"",error:"",timeout:"",type:""},b;for(b in d)void 0!=d[b]&&(a[b]=d[b]);var e=this.createCORSRequest(a.method,a.url);e?(e.onload="json"==a.type?function(){a.onload(JSON.parse(e.responseText))}:function(){a.onload(e.responseText)},e.onerror=function(){""!=a.error&&a.error()},e.onprogress=function(){},e.ontimeout=function(){""!=a.timeout&&a.timeout()},e.send()):alert("CORS not supported")},createCORSRequest:function(d,
a){var b=new XMLHttpRequest;"withCredentials"in b?b.open(d,a,!0):"undefined"!=typeof XDomainRequest?(b=new XDomainRequest,b.open(d,a)):b=null;return b}};